# Generated by Django 6.0.3 on 2026-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ai_diagnostics',
            field=models.TextField(blank=True, help_text='JSON строка или текст ИИ-заключения'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='post_treatment_status',
            field=models.TextField(blank=True, help_text='Состояние после лечения'),
        ),
    ]
