# Generated by Django 6.0.3 on 2026-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment_ai_diagnostics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='anamnesis',
            field=models.TextField(blank=True, help_text='Предварительный анамнез от пациента (жалобы)'),
        ),
    ]
