# Generated by Django 6.0.3 on 2026-04-02 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment_anamnesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('primary', 'Первичный'), ('secondary', 'Вторичный'), ('follow_up', 'Повторный'), ('preventive', 'Профилактический'), ('emergency', 'Экстренный'), ('consultation', 'Консультация')], default='primary', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('analysis', 'Анализ'), ('xray', 'Рентген / Снимок'), ('ultrasound', 'УЗИ'), ('mri', 'МРТ / КТ'), ('ekg', 'ЭКГ'), ('prescription', 'Рецепт'), ('conclusion', 'Заключение врача'), ('referral', 'Направление'), ('certificate', 'Справка'), ('other', 'Другое')], default='analysis', max_length=20)),
                ('title', models.CharField(help_text='Название документа', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание: дата, причина, комментарии')),
                ('file', models.FileField(upload_to='patient_docs/%Y/%m/')),
                ('doc_date', models.DateField(blank=True, help_text='Дата документа (анализа и т.д.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
