services:
  - type: web
    name: medai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn medai.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
